# Generated by Django 4.1 on 2022-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="category"),
                ),
                ("serial", models.IntegerField(blank=True, null=True, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
