# Generated by Django 4.1 on 2022-09-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productphoto",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_photo",
                to="product.product",
            ),
        ),
    ]
