# Generated by Django 4.1 on 2022-09-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
